FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Set the working directory 
WORKDIR /app

# Copy the package.json and pnpm-lock.yaml files
COPY ./package.json ./
COPY ./pnpm-lock.yaml ./

# Install dependencies using pnpm
RUN pnpm install

COPY . .

# Build the application
RUN pnpm run build

FROM nginx:stable-alpine

COPY --from=base /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
