services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ../db/.env.local
    ports:
      - 5432:5432
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    networks:
      - my-network
  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile.local
    volumes:
      - ../frontend:/app
      - /app/node_modules
    restart: always
    ports:
      - '8081:8081'
    networks:
      - my-network
  backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile.local
    volumes:
      - ../backend:/app
      - /app/node_modules
    restart: always
    ports:
      - '8080:8080'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
