services:
  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile.local
    volumes:
      - ../frontend:/app
      - /app/node_modules
    restart: always
    ports:
      - '8081:8081'
    networks:
      - my-network
  backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile.local
    volumes:
      - ../backend:/app
      - /app/node_modules
    restart: always
    ports:
      - '8081:8081'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
