services:
  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile.prod
    restart: unless-stopped
    ports:
      - '8081:80'
    networks:
      - my-network
  backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile.prod
    restart: unless-stopped
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
