services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    networks:
      - my-network
  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile.prod
    restart: unless-stopped
    ports:
      - '8081:80'
    networks:
      - my-network
  backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile.prod
    restart: unless-stopped
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
