FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Set the working directory 
WORKDIR /app

# Copy the package.json and pnpm-lock.yaml files
COPY ./package.json ./
COPY ./pnpm-lock.yaml ./
COPY ./tsconfig.json ./

COPY .env ./

# Install dependencies using pnpm
RUN pnpm install

COPY ./src ./src

RUN pnpm run build

EXPOSE 8081

# Run the development server
CMD ["pnpm", "run", "start"]